image:
  repository: localhost:32000/artci
  tag: latest
  pullPolicy: Always

ingress:
  className: public
  hosts:
    - host: artci.cloudyapp.net
      paths:
        - path: /
          pathType: Prefix

# In dev, we might want to expose Postgres via NodePort or just use the ClusterIP
postgresql:
  image:
    repository: bitnamilegacy/postgresql
    tag: "16.6.0-debian-12-r2"
  auth:
    password: "devpassword"
