image:
  repository: localhost:32000/artci
  tag: latest
  pullPolicy: Always

ingress:
  className: public
  hosts:
    - host: artci.local
      paths:
        - path: /
          pathType: Prefix

# In dev, we might want to expose Postgres via NodePort or just use the ClusterIP
postgresql:
  auth:
    password: "devpassword"
