image:
  repository: localhost:32000/artci
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  className: public
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: app.artci.ci
      paths:
        - path: /
          pathType: Prefix
    - host: jinforme.artci.ci
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: artci-tls
      hosts:
        - app.artci.ci
        - jinforme.artci.ci

# In dev, we might want to expose Postgres via NodePort or just use the ClusterIP
postgresql:
  image:
    repository: bitnamilegacy/postgresql
    tag: "16.6.0-debian-12-r2"
  auth:
    password: "devpassword"
